extends Node

signal PLAYER_MOVEMENT_DIRECTION_UPDATE
signal PLAYER_OUT_OF_BOUNDS
signal PLAYER_RESPAWNED
signal PLAYER_BALL_SIZE_CHANGED
signal ADD_OBJECT_TO_PLAYER_BALL
signal OBJECT_PUNTED_BALL

signal ADD_PEACH_MESSAGE_TO_QUEUE
signal DISPLAY_PEACH_MESSAGE
signal REMOVE_PEACH_MESSAGE
signal PEACH_MESSAGE_REMOVED
signal MUTE_PEACH

signal SET_MOUSE_MODE
signal SET_UI_MODE
signal SET_PP_MODE

signal DIALOGUE_DONE

signal NOTIFY_LEVEL_LOADED
signal NOTIFY_LEVEL_NUB_SELECTED
signal NOTIFY_SAVE_DATA_UPDATED

signal PAUSE_GAME
signal LOAD_LEVEL

signal TOGGLE_BGM
signal PLAY_BGM

signal BLAST_PLAYER

signal DRAW_CURTAIN
signal CURTAIN_DRAWN
signal OPEN_CURTAIN
signal CURTAIN_OPENED

signal FINAL_TIME

#When bowser is collected
signal NOTIFY_BOWSER_COLLECTED
#whenthe level is complete (essentially after GOAL is emitted, but this includes level info)
signal LEVEL_COMPLETE

signal UP_MOON
